---
title: "Opioid Crisis in Indiana - Team 3"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# Setup, initialize root directory for data location and tool libraries

knitr::opts_knit$set(root.dir = "C:/Users/Joshua Ho/Desktop/Y3T1 - Engineering/BMEG 372/Overdoes Lifeline/")
setwd("C:/Users/Joshua Ho/Desktop/Y3T1 - Engineering/BMEG 372/Overdoes Lifeline")

library(flexdashboard)
library(shiny)
library(leaflet)
library(highcharter)
library(sf)
library(ggplot2)
library(maps)
library(dplyr)
library(readxl)
library(stringr)
library(knitr)
library(raster)
library(rgeos)

```

```{r}
# Convert map library data of indiana to an sf multipolygon object
indiana.sf <- st_as_sf(map(database = "county", regions = "indiana", plot = FALSE, fill = TRUE), crs = 4326, group = TRUE)
indiana.sf$ID <- gsub("indiana,","",indiana.sf$ID)

#Extract number of programs
indiana.programs <- read_excel("Indiana County Population Data - US Census.xlsx", sheet = "Programs", skip  = 2, col_names = T)
colnames(indiana.programs) <- colnames(read_excel("Indiana County Population Data - US Census.xlsx", sheet = "Programs", col_names = T))
indiana.programs = indiana.programs[-nrow(indiana.programs),]
indiana.programs$Name = indiana.sf$ID

# Retrieve Kits Distributed and Engagement Data for Heatmap
indiana.distribution <- read.csv("distribution.csv")

# Extract Normalized Data for Normalized Heatmap 3
deaths.data <- read_excel("Indiana County Population Data - US Census.xlsx", 
                          sheet = "Race and Age Data 2016-2019",skip = 2)

norm.deaths = deaths.data[-1,12]

# Binding of Normalized Deaths by County
indiana.sf<- cbind(indiana.sf, norm.deaths)
names(indiana.sf)[names(indiana.sf) == 'Total.Opioid.Overdose.Deaths...12'] <- "normalized_deaths"

## JACQUELINE

# Extract Race Data and Age Data for Race and Age Graphs
cdc.race.overdose <- read.csv("cdc-race-overdose.csv")
first.responder.race.age <- read.csv("first-responder-race-age.csv")
cdc.age.overdose <- read.csv("CDC Age Data.csv")
raceData <- merge(cdc.race.overdose, first.responder.race.age, by="誰..County")
ageData <- merge(cdc.age.overdose, first.responder.race.age, by="誰..County")

names(raceData)[names(raceData) == "誰..County"] <- 'County'
names(ageData)[names(ageData) == "誰..County"] <- 'County'

raceData$County = indiana.sf$ID
ageData$County = indiana.sf$ID

## BENJIE

# Extracting Deaths vs. Time
data <- as.matrix(read_excel('Indiana County Population Data - US Census.xlsx', 
                             sheet = "Total Opioid Overdoses by Year"))
colnames(data) <- NULL

output_data <- data.frame(deaths = integer(), deaths.normalized = double(), 
                          year = integer(), county = character())
for (row in 3:nrow(data)){
  
  for (col in 1:5){
    
    if (col == 1){
      
      county <- tolower(substr(data[row, col], 1, nchar(data[row, col]) - 7))
      
    } else{
    
      if (col == 2){
        
        year <- 2016
        
      } else if (col == 3) {
        
        year <- 2017
       
      } else if (col == 4){
        
        year <- 2018
        
      } else if (col == 5) {
        
        year <- 2019
        
      } else {
        
        year <- 2020
       
      }
      
      output_data[nrow(output_data) + 1,] <- (list(as.numeric(data[row, col]), 
                                                   as.numeric(data[row, col + 5]), year, county))
    }
  }
}

distribution <- read.csv('distribution-fr.csv')

# Binding of kits distribution, engagement and programs to spatial data
indiana.sf<- cbind(indiana.sf, kits = indiana.distribution$Kits.Distributed, engagement = indiana.distribution$Engagement, programs = indiana.programs$'Total Number of Programs')

## EMILY

# Summary and Rankings Data Sorting

# Read data from shared files
kit.data <- read.csv("distribution.csv")
nums <- 1:92

# Death data frame
deathdata <- data.frame(deaths.data$County, deaths.data$`Total Opioid Overdose Deaths...2`)
deathdata <- deathdata[-1,]
deathdata[17,1] <- "DeKalb County"
deathdata[46,1] <- "LaPorte County"

# Normalized death data frame
normalizeddeath <- data.frame(deaths.data$County, deaths.data$`Total Opioid Overdose Deaths...12`)
normalizeddeath <- normalizeddeath[-1,]
normalizeddeath[17,1] <- "DeKalb County"
normalizeddeath[46,1] <- "LaPorte County"

# Rank kit data from lowest to highest and deaths data from highest to lowest
orderkitdata <- kit.data[order(kit.data$Kits.Distributed),]
ordernormalizedeathsdata <- normalizeddeath[order(-normalizeddeath$deaths.data..Total.Opioid.Overdose.Deaths...12.),]
orderdeathsdata <- deathdata[order(deathdata$deaths.data..Total.Opioid.Overdose.Deaths...2.),]
orderkitdata <- cbind(orderkitdata, "Kit Distribution Ranking (Lowest to Highest)" =nums)
ordernormalizedeathsdata <- cbind(ordernormalizedeathsdata, 
                                  "Normalized Deaths per 100 000 Ranking (Highest to Lowest)" =nums)
orderdeathsdata <- cbind(orderdeathsdata, "Deaths Ranking (Highest to Lowest)"= nums)

# Fix county names
orderkitdata[,1] <- str_to_title(orderkitdata[,1])
ordernormalizedeathsdata[,1] <- str_remove(ordernormalizedeathsdata[,1], "County")
orderdeathsdata[,1] <- str_remove(orderdeathsdata[,1], "County")
orderkitdata[34,1] <- "DeKalb"
orderkitdata[39,1] <- "LaGrange"
orderkitdata[55,1] <- "LaPorte"

# Order data by county
ordercountykitdata <- orderkitdata[order(orderkitdata$County),]
ordercountynormalizeddeathsdata <- ordernormalizedeathsdata[order(ordernormalizedeathsdata$deaths.data.County),]
ordercountydeathsdata <- orderdeathsdata[order(orderdeathsdata$deaths.data.County),]

# Create merged dataframe
rankings <-("County" = ordercountykitdata$County)
rankings <- cbind("County" = rankings, "Kit Distribution Ranking (Lowest to Highest)" = ordercountykitdata$`Kit Distribution Ranking (Lowest to Highest)`)
rankings <- cbind(rankings, "Normalized Deaths Ranking (Highest to Lowest)" = ordercountynormalizeddeathsdata$`Normalized Deaths per 100 000 Ranking (Highest to Lowest)`)

# Summary
programs <- read_excel("Indiana County Population Data - US Census.xlsx", sheet = "Programs")
programs <- programs[-1,]
programs <- programs[-1,]
programs <- head(programs, -1)

# Compiling relevant data
compiledData <-(indiana.sf$ID)
compiledData <- cbind("ID"=compiledData, ordercountykitdata, ordercountydeathsdata)
programs <- cbind(programs, "ID" = indiana.sf$ID)

# Indiana Spatial Zoom Data
us <- getData("GADM",country="USA",level=2)
indiana <- us[us$NAME_1 %in% "Indiana",]
centers <- data.frame(gCentroid(indiana, byid = TRUE))
centers$region <- row.names(indiana)
centers$county <- indiana$NAME_2
centers = centers[-46,] # Remove lake michigan
```


Column {data-Width=320, .sidebar}
-----------------------------------------------------------------------
```{r}
# Create sidebar for ranked list features and input bar to control heatmap options

selectInput("density_adjust", label = "Density Overlay Adjustment", choices = c("Kits Distributed", "Active Overdose Programs", "Normalized Overdose Deaths"), selected = "Kits Distributed")

kable(rankings, caption = "County Rankings by Feature")

```

Row {data-height=450}
-----------------------------------------------------------------------

### Map

```{r}
# Generate indiana map, as well as create heatmap through filling by data

output$map <- renderLeaflet({

  
  if(input$density_adjust == "Kits Distributed"){
    
    data.set = indiana.sf$kits
    pal_fun <- colorNumeric("YlOrRd", NULL, n = 5)
    data.title = paste0("<center>", "Kits Distributed", "<br/>", "by County")
    p_popup <- paste0(
      "<center>", str_to_title(indiana.sf$ID),"</center>" , "<br/>", "<strong>Kits Distributed: </strong>", indiana.sf$kits, "<br>", "<strong>Engagement: </strong>", indiana.sf$engagement)
    
  } else if(input$density_adjust == "Active Overdose Programs"){
    
    data.set = indiana.sf$programs
    pal_fun <- colorNumeric("YlGnBu", NULL, n = 5)
    data.title = paste0("<center>", "Total Active", "<br/>", "Programs", "<br/>", "by County")
    p_popup <- paste0(
      "<center>", str_to_title(indiana.sf$ID),"</center>" , "<br/>", "<strong>Total Active Programs: </strong>", indiana.sf$programs)
    
  } else if(input$density_adjust == "Normalized Overdose Deaths"){
    
    data.set = indiana.sf$normalized_deaths
    pal_fun <- colorNumeric("YlGn", NULL, n = 5)
    data.title = paste0("<center>", "Normalized Overdose", "<br/>", "Deaths", "<br/>", "by County")
    p_popup <- paste0(
      "<center>", str_to_title(indiana.sf$ID),"</center>" , "<br/>", "<strong>Normalized Deaths: </strong>", indiana.sf$normalized_deaths)
    
  }

  leaflet(indiana.sf) %>%
    addPolygons( 
      layerId = ~ID, 
      stroke = TRUE, 
      weight = 0.5,
      fillColor = ~pal_fun(data.set),
      fillOpacity = 0.8, smoothFactor = 0.5,
      popup = p_popup) %>%
    addLegend("bottomright",  # location
            pal=pal_fun,    # palette function
            values= ~data.set,  # value to be passed to palette function
            title = data.title) # legend title

})

# Create clickable event by designating a eventReactive

click_tract <- eventReactive(input$map_shape_click, {
  
    x <- input$map_shape_click
    
    y <- x$id
    
    return(y)

})

# Set condition for when zoom is close enough, county names will appear for easier search

observeEvent(
    eventExpr = input$map_zoom, 
    {
      print(input$map_zoom)           # Display zoom level in the console
      leafletProxy(
        mapId = "map"
      ) %>% 
        clearMarkers() %>%
        addLabelOnlyMarkers(data = centers,
                    lng = ~x, lat = ~y, label = if(input$map_zoom > 8) ~county,
                    labelOptions = labelOptions(noHide = TRUE, direction = 'top', textOnly = TRUE))
    }
  )

# Set conditions for when county polygon is clicked to highlight the shape, and remove when a new one is clicked.

observe({
  
  req(click_tract()) # do this if click_tract() is not null
  
  # Add the clicked tract to the map in aqua, and remove when a new one is clicked
  map <- leafletProxy('map') %>%
      removeShape('htract') %>%
      addPolygons(data = indiana.sf[indiana.sf$ID == click_tract(), ], fill = FALSE,
                  color = '#00FFFF', opacity = 1, layerId = 'htract')
  })

# On clicking, set each click to reference a unique ID mapped to each polygon

data_for_chart <- reactive({

  return(indiana.sf[indiana.sf$ID == click_tract(), ])

})


leafletOutput('map') 


```

### Summary

```{r}

output$summary <- renderTable({
  
  county =  data_for_chart()$ID
  
 index <- which(programs$ID==county)
colname <- colnames(programs[which(programs[index,]==1)])
if(length(colname) == 0){
  colname <- "No Active Programs"
} else if (colname[1] == "Total Number of Programs") {
  colname <- colname[-1]
}
colnametable <- paste(colname, collapse =", ")
rownamesdata <- c("County:","Overdose Deaths", "Deaths Ranking (Highest to Lowest number of deaths)", "Kits Distributed", "Kits Ranking (Lowest to Highest number of kits distributed)", "Number of Active Programs", "Active Programs")
tabledataframe<- data.frame("Summary"=matrix(ncol = 1, nrow = 7))
tabledataframe[1,1] <- (compiledData$County[which(compiledData$ID == county)])
tabledataframe[2,1] <- (compiledData$deaths.data..Total.Opioid.Overdose.Deaths...2.[which(compiledData$ID == county)])
tabledataframe[3,1] <- (compiledData$`Deaths Ranking (Highest to Lowest)`[which(compiledData$ID == county)])
tabledataframe[4,1] <- (compiledData$Kits.Distributed[which(compiledData$ID == county)])
tabledataframe[5,1] <- (compiledData$`Kit Distribution Ranking (Lowest to Highest)`[which(compiledData$ID == county)])
tabledataframe[6,1] <- (programs$`Total Number of Programs`[which(programs$ID == county)])
tabledataframe[7,1] <- (colnametable)
rownames(tabledataframe) <- rownamesdata
tabledataframe <- as.data.frame(tabledataframe)
  
}, rownames = TRUE)

tableOutput('summary')

```

Row {data-height=550, .tabset}
-----------------------------------------------------------------------

### Age

```{r}

output$age <- renderHighchart({

 county = data_for_chart()$ID
 age.table = data.frame(
    Age = c("<15", "15-24", "25-34", "35-44", "45-54", "55-64", ">60"),
    CDCData = c(ageData[which(ageData$County == county), "AC1"], 
                ageData[which(ageData$County == county), "AC2"], 
                ageData[which(ageData$County == county), "AC3"], 
                ageData[which(ageData$County == county), "AC4"], 
                ageData[which(ageData$County == county), "AC5"], 
                ageData[which(ageData$County == county), "AC6"], 
                ageData[which(ageData$County == county), "AC7"]),
    ODLData = c(ageData[which(ageData$County == county), "Under.15"], 
                ageData[which(ageData$County == county), "X15.to.24"], 
                ageData[which(ageData$County == county), "X25.to.34"], 
                ageData[which(ageData$County == county), "X35.to.44"], 
                ageData[which(ageData$County == county), "X45.to.54"], 
                ageData[which(ageData$County == county), "X55.to.64"], 
                ageData[which(ageData$County == county), "Over.65"])
    )
  
  highchart() %>% 
    hc_chart(type = "column") %>%
    hc_title(text = "CDC Overdose Deaths and ODL Kits Distributed by Age (2016-2019)") %>% 
    hc_subtitle(text = paste(county, "county")) %>%
    hc_xAxis(categories = age.table$Age) %>%
    hc_add_series(name="CDC Recorded Overdose Deaths",
                data = age.table$CDCData) %>%
    hc_add_series(name="ODL First Responder Kits Distribution",
                data = age.table$ODLData) %>%
    hc_colors(c("#0073C2FF", "#EFC000FF"))
  
  
})

highchartOutput('age')

```

### Race

```{r}
# Create Race Graph, bar chart by race with each race having two columns describing CDC cited deaths and first responder kits distributed

output$race <- renderHighchart({
  
  county = data_for_chart()$ID
  bs.table = data.frame(
    Race = c("White", "Black"),
    CDCData = c(raceData[which(raceData$County == county), "CDC.White"], 
                raceData[which(raceData$County == county), "CDC.Black"]),
    ODLData = c(raceData[which(raceData$County == county), "White"], 
                raceData[which(raceData$County == county), "Black"])
  )

  highchart() %>% 
    hc_chart(type = "bar") %>%
    hc_title(text = "CDC Overdose Deaths and ODL Kits Distributed by Race (Normalized per 100 000)") %>% 
    hc_subtitle(text = paste(county, "county")) %>%
    hc_plotOptions(column = list(stacking = "normal")) %>%
    hc_xAxis(categories = bs.table$Race) %>%
    hc_add_series(name="CDC Recorded Overdose Deaths (2016 - 2019)",
                  data = bs.table$CDCData) %>%
    hc_add_series(name="ODL First Responder Kits Distribution",
                  data = bs.table$ODLData) %>%
    hc_colors(c("#0073C2FF", "#EFC000FF"))

})

highchartOutput('race')


```

### Deaths vs. Time

```{r}

output$deaths <- renderHighchart({
  
  x = data_for_chart()$ID
  countyData <- subset(output_data, county == x)
  countyDistribution <- subset(distribution, County == x)
  highchart() %>%
    hc_title(text = "CDC Reported Overdose Deaths (2016 - 2019)") %>%
    hc_subtitle(text = paste(x, "county")) %>%
    hc_add_series(name="Kit Distribution", data = countyDistribution$Kits.Distributed, type = "column") %>%
    hc_add_series(name="Deaths", data = countyData$deaths, type = "line") %>%
    hc_add_series(name="Deaths per 100,000 People", data = countyData$deaths.normalized, type = "line") %>%
    hc_xAxis(categories = countyData$year) %>%
    hc_yAxis(title = "Number of Deaths") %>%
    hc_colors(c("#D3D3D3", "#0073C2FF", "#EFC000FF"))
  
})

highchartOutput('deaths')

```








