---
title: "Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "C:/Users/Joshua Ho/Desktop/Y3T1 - Engineering/BMEG 372/Overdoes Lifeline/")
setwd("C:/Users/Joshua Ho/Desktop/Y3T1 - Engineering/BMEG 372/Overdoes Lifeline/R-spatial")

library(flexdashboard)
library(shiny)
library(leaflet)
library(highcharter)
library(sf)

vec = c(10,4,3,15,2,8,9,5,4,12)
vec2 =  c(4,9,8,12,5,3,7,6,25,10)
test_lsit =  list(list(vec))

philly_crimes_sf <-  st_read("data/PhillyCrimerate", quiet = FALSE)
philly_WGS84 <- st_transform(philly_crimes_sf, 4326)
philly_WGS84 <- philly_WGS84[,!names(philly_WGS84) %in% c("tract_area")]

amount1 =  data.frame(matrix(ncol = 1, nrow = nrow(philly_WGS84)))
amount2 =  data.frame(matrix(ncol = 1, nrow = nrow(philly_WGS84)))

for(i in 1:nrow(philly_WGS84)){
  
  amount1[i,1] = list(list(vec))
  amount2[i,1] = list(list(vec2))
  
}

colnames(amount1) <- "Crime_A"
colnames(amount2) <- "Crime_B"

philly_WGS84 <- cbind(philly_WGS84, amount1, amount2)

#philly_wgs84 gemoetry has lists of longitude (x) then latitude (y)

```

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput("density_adjust", label = "Density Overlay Adjustment", choices = c("Homicide Rate", "Number of Homicides"), selected = "Homicide Rate")

```


Row {data-height=500}
-----------------------------------------------------------------------

```{r}
output$map <- renderLeaflet({
  
  if(input$density_adjust == "Homicide Rate"){
    
    data.set = philly_WGS84$homic_rate
    pal_fun <- colorQuantile("YlOrRd", NULL, n = 5)
    data.title = 'Philadelphia homicide density per sqkm'
    p_popup <- paste0(
      "<center>", philly_WGS84$GEOID10,"</center>" , "<br/>", "<strong>Homicide Density: </strong>", philly_WGS84$homic_rate)
    
  } else if(input$density_adjust == "Number of Homicides"){
    
    data.set = philly_WGS84$n_homic
    pal_fun <- colorNumeric("Purples", NULL, n = 5)
    data.title = 'Philadelphia Number of Homicides'
    p_popup <- paste0("<strong>Homicide Amount: </strong>", philly_WGS84$n_homic)
    
  }
  
  leaflet(philly_WGS84) %>%
    addPolygons( 
      layerId = ~GEOID10, 
      stroke = TRUE, 
      weight = 0.5,
      fillColor = ~pal_fun(data.set),
      fillOpacity = 0.8, smoothFactor = 0.5,
      popup = p_popup) %>%
    
    addLegend("bottomright",  # location
            pal=pal_fun,    # palette function
            values= ~data.set,  # value to be passed to palette function
            title = data.title) # legend title

})

click_tract <- eventReactive(input$map_shape_click, {
  
    x <- input$map_shape_click
    
    y <- x$id
    
    return(y)

})

observe({
  
  req(click_tract()) # do this if click_tract() is not null
  
  # Add the clicked tract to the map in aqua, and remove when a new one is clicked
  map <- leafletProxy('map') %>%
      removeShape('htract') %>%
      addPolygons(data = philly_WGS84[philly_WGS84$GEOID10 == click_tract(), ], fill = FALSE,
                  color = '#00FFFF', opacity = 1, layerId = 'htract')
  })

data_for_chart <- reactive({
  
  if(input$density_adjust == "Homicide Rate"){
    
    
    
    
    
  }else if(input$density_adjust == "Number of Homicides"){
    
    
    
  }

  return(philly_WGS84[philly_WGS84$GEOID10 == click_tract(), ])

})


leafletOutput('map')  

```

Row {data-height=500, .tabset}
-----------------------------------------------------------------------
### Chart 1

```{r}

output$chart <- renderHighchart({
  
  highchart() %>%
    hc_chart(type = 'bar') %>%
    hc_add_series(data = c(data_for_chart()$crime_A, data_for_chart()$crime_B)) %>% 
    hc_title(text = data_for_chart()$GEOID10)

})

highchartOutput('chart')




```

### Chart 2
```{r}

output$chart2 <- renderHighchart({

  highchart() %>%
    hc_chart(type = 'bar') %>%
    hc_add_series(data = data_for_chart()$homic_rate) %>% 
    hc_title(text = data_for_chart()$GEOID10)

})

highchartOutput('chart2')

```

### Chart 3
```{r}

output$chart3 <- renderHighchart({

  highchart() %>%
    hc_chart(type = 'scatter') %>%
    hc_add_series(data = data_for_chart()$homic_rate) %>% 
    hc_title(text = data_for_chart()$GEOID10)

})

highchartOutput('chart3')

```

Row {data-height=500}
-----------------------------------------------------------------------

### Data

```{r}
print(philly_WGS84)
```




